CREATE TABLE portal_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'employee')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE portal_users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON portal_users FROM anon, authenticated;

-- Seed accounts matching the previous localStorage defaults (change these after setup).
-- Passwords: admin/5678, employee/1234 — hashed with scrypt (salt:hash hex).
INSERT INTO portal_users (username, password_hash, role) VALUES
  ('admin', 'a19a99d21d3d27b8eb7d320dda7d524c:ef39c49a573c157bed515d523d95174d7ce485730a192a5dca852490cd7ce0eb5ee5e596924e23ecb4ce8dea649bfdf244612e4008672655cec701e9ca355867', 'admin'),
  ('employee', 'cb8cf5bd6123367197a7d8e1c96d76c8:fe392c7d397280d8fbfb817ded4d4629e95bb0e1f918c5466bfc4c66f6e065a6b2f1372a462087985ab5103fc686cba70ff0b00077f8a2dff3252a7c706742eb', 'employee');
